baseURL = 'https://prisonpc.com/'
languageCode = 'en-au'
title = 'PrisonPC'
#theme = 'pehtheme-hugo'
theme = 'up-business-theme'

[params]
title = "PrisonPC"
description = "Secure Prisoner Interactive Learning System"

# ----------

images = [
    "images/carousel_1.jpg",
    "images/carousel_2.jpg",
    "images/carousel_3.jpg",
    "images/carousel_4.jpg",
]
location = [
    "P.O.Box 5178, Hughesdale, Vic 3166, Australia",
    "Cyber IT Solutions Pty Ltd, Suite 49, Erasmus Business Park, 45 Riversdale Road, Hawthorn, Victoria 3122, Australia"
]
copyright = "© 2024 Cyber IT Solutions Pty Ltd"
[params.favicons]
themeColor = "#FFFFFF"
backgroundColor = "#FFFFFF"
faviconColor = "#000000"
[params.social]
#dribbble = "#"
#instagram = "#"
#facebook = "#"
#twitter = "#"

[[params.contact]]
content = "info@prisonpc.com"
url = "mailto:info@prisonpc.com"
[[params.contact]]
content = "+613 7019 4225"
url = "tel:+61370194225"

[menus]

[[menus.main]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.main]]
name = "Business Drivers"
url = "/business-drivers"
weight = 2

[[menus.main]]
name = "Security"
url = "/security"
weight = 3

[[menus.main]]
name = "Features"
url = "/features"
weight = 4

#[[menus.main]]
#name = "Blog"
#url = "/posts"
#weight = 5

#[[menus.buttons]]
#name = "Book a call"
#url = "/#"
#weight = 5
#pre = "btn btn-primary text-light"

[[menus.footer]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.footer]]
name = "Business Drivers"
url = "/business-drivers"
weight = 2

[[menus.footer]]
name = "Security"
url = "/security"
weight = 3

[[menus.footer]]
name = "Features"
url = "/features"
weight = 4

#[[menus.footer]]
#name = "Blog"
#url = "/posts"
#weight = 5

[taxonomies]
series = "series"
tags = "tags"
